services:
  backend:
    build: .
    command: fastapi dev --host 0.0.0.0 --port 5175 src/fastapi_celery/main.py
    ports:
      - "5175:5175"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  worker:
    build: .
    command: celery -A src.fastapi_celery.worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      - BACKEND_URL=http://backend:5175
      - APP_PORT=5174
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  redis:
    image: redis:7-alpine

volumes:
  redis_data:
